[vars]
swift_dirs = "Sources/ Tests/ TestApps/"

[tasks.build]
description = "Build debug binary"
run = "swift build"

[tasks.dev]
description = "Build debug binary and run"
usage = 'arg "<command>" var=#true help="forepaw subcommand and arguments"'
run = "swift build && swift run forepaw ${usage_command}"

[tasks.test]
run = "swift test"

[tasks.check]
description = "Lint and test"
run = [
    "xcrun swift-format lint -r {{vars.swift_dirs}} --strict",
    "swift test",
]

[tasks.lint]
run = "xcrun swift-format lint -r {{vars.swift_dirs}} --strict"

[tasks.fmt]
description = "Auto-format Swift files"
run = "xcrun swift-format format -i -r {{vars.swift_dirs}}"

[tasks.release-build]
description = "Build release binary"
run = "swift build -c release"
