#!/usr/bin/env bash
# Generates crates/forepaw/src/platform/linux/role.rs from res/atspi-constants.h.
#
# Usage:
#   ./res/generate_atspi_roles.sh          # prints to stdout (pipe to file)
#   ./res/generate_atspi_roles.sh > file   # redirect to file
#
# Source of truth: res/atspi-constants.h (copied from
#   https://gitlab.gnome.org/GNOME/at-spi2-core/-/raw/HEAD/atspi/atspi-constants.h)
#
# The role mapping is opinionated (AT-SPI2 native names → `Role` variants).
# The enum values are factual. Both are generated so CI can detect drift.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
HEADER="$SCRIPT_DIR/atspi-constants.h"

if [[ ! -f "$HEADER" ]]; then
  echo "ERROR: $HEADER not found" >&2
  exit 1
fi

awk '
BEGIN {
  in_enum = 0
  val = 0
  print "// Generated by res/generate_atspi_roles.sh from res/atspi-constants.h."
  print "// Source: https://gitlab.gnome.org/GNOME/at-spi2-core/-/raw/HEAD/atspi/atspi-constants.h"
  print "// To regenerate: bash res/generate_atspi_roles.sh > crates/forepaw/src/platform/linux/role.rs"
  print ""
  print "#![expect("
  print "    clippy::match_same_arms,"
  print "    reason = \"AT-SPI2 roles legitimately map to the same Role\""
  print ")]"
  print ""
  print "use crate::core::role::Role;"
  print ""
  print "/// Map AT-SPI2 role values to cross-platform [`Role`] values."
  print "///"
  print "/// Generated from `res/atspi-constants.h`. See the generator for the mapping."
  print "#[must_use]"
  print "#[expect(clippy::too_many_lines, reason = \"generated match arm list\")]"
  print "#[rustfmt::skip]"
  print "pub fn atspi_role_to_role(role: u32) -> Role {"
  print "    match role {"
}

/typedef enum/ { in_enum = 1; next }
/^[[:space:]]*}/ && in_enum { in_enum = 0; next }

in_enum && /^[[:space:]]*ATSPI_ROLE_/ && !/=/ {
  gsub(/^[[:space:]]+/, "")
  gsub(/[[:space:]]+$/, "")
  gsub(/,$/, "")
  name = $1
  sub(/^ATSPI_ROLE_/, "", name)
  printf "        %d => %s,\n", val, ax[name]
  val++
}

END {
  print "        _ => Role::Unknown,"
  print "    }"
  print "}"
}

BEGIN {
  ax["INVALID"]        = "Role::Unknown"
  ax["ACCELERATOR_LABEL"] = "Role::Unknown"
  ax["ALERT"]          = "Role::Alert"
  ax["ANIMATION"]      = "Role::Unknown"
  ax["ARROW"]          = "Role::Unknown"
  ax["CALENDAR"]       = "Role::Calendar"
  ax["CANVAS"]         = "Role::Unknown"
  ax["CHECK_BOX"]      = "Role::CheckBox"
  ax["CHECK_MENU_ITEM"] = "Role::MenuItemCheckBox"
  ax["COLOR_CHOOSER"]  = "Role::ColorChooser"
  ax["COLUMN_HEADER"]  = "Role::ColumnHeader"
  ax["COMBO_BOX"]      = "Role::ComboBox"
  ax["DATE_EDITOR"]    = "Role::DatePicker"
  ax["DESKTOP_ICON"]   = "Role::Unknown"
  ax["DESKTOP_FRAME"]  = "Role::Unknown"
  ax["DIAL"]           = "Role::Unknown"
  ax["DIALOG"]         = "Role::Dialog"
  ax["DIRECTORY_PANE"] = "Role::Unknown"
  ax["DRAWING_AREA"]   = "Role::Unknown"
  ax["FILE_CHOOSER"]   = "Role::Unknown"
  ax["FILLER"]         = "Role::Unknown"
  ax["FOCUS_TRAVERSABLE"] = "Role::Unknown"
  ax["FONT_CHOOSER"]   = "Role::Unknown"
  ax["FRAME"]          = "Role::Frame"
  ax["GLASS_PANE"]     = "Role::Unknown"
  ax["HTML_CONTAINER"] = "Role::Unknown"
  ax["ICON"]           = "Role::Icon"
  ax["IMAGE"]          = "Role::Image"
  ax["INTERNAL_FRAME"] = "Role::InternalFrame"
  ax["LABEL"]          = "Role::Label"
  ax["LAYERED_PANE"]   = "Role::Unknown"
  ax["LIST"]           = "Role::List"
  ax["LIST_ITEM"]      = "Role::Unknown"
  ax["MENU"]           = "Role::Menu"
  ax["MENU_BAR"]       = "Role::MenuBar"
  ax["MENU_ITEM"]      = "Role::MenuItem"
  ax["OPTION_PANE"]    = "Role::Unknown"
  ax["PAGE_TAB"]       = "Role::Tab"
  ax["PAGE_TAB_LIST"]  = "Role::TabGroup"
  ax["PANEL"]          = "Role::Group"
  ax["PASSWORD_TEXT"]  = "Role::SecureTextField"
  ax["POPUP_MENU"]     = "Role::Menu"
  ax["PROGRESS_BAR"]   = "Role::ProgressIndicator"
  ax["BUTTON"]         = "Role::Button"
  ax["RADIO_BUTTON"]   = "Role::RadioButton"
  ax["RADIO_MENU_ITEM"] = "Role::MenuItemRadio"
  ax["ROOT_PANE"]      = "Role::Unknown"
  ax["ROW_HEADER"]     = "Role::RowHeader"
  ax["SCROLL_BAR"]     = "Role::ScrollBar"
  ax["SCROLL_PANE"]    = "Role::Unknown"
  ax["SEPARATOR"]      = "Role::Separator"
  ax["SLIDER"]         = "Role::Slider"
  ax["SPIN_BUTTON"]    = "Role::Incrementor"
  ax["SPLIT_PANE"]     = "Role::Unknown"
  ax["STATUS_BAR"]     = "Role::StatusBar"
  ax["TABLE"]          = "Role::Table"
  ax["TABLE_CELL"]     = "Role::Cell"
  ax["TABLE_COLUMN_HEADER"] = "Role::ColumnHeader"
  ax["TABLE_ROW_HEADER"] = "Role::RowHeader"
  ax["TEAROFF_MENU_ITEM"] = "Role::MenuItem"
  ax["TERMINAL"]       = "Role::Unknown"
  ax["TEXT"]           = "Role::TextArea"
  ax["TOGGLE_BUTTON"]  = "Role::Switch"
  ax["TOOL_BAR"]       = "Role::Toolbar"
  ax["TOOL_TIP"]       = "Role::Tooltip"
  ax["TREE"]           = "Role::Outline"
  ax["TREE_TABLE"]     = "Role::Unknown"
  ax["UNKNOWN"]        = "Role::Unknown"
  ax["VIEWPORT"]       = "Role::Unknown"
  ax["WINDOW"]         = "Role::Window"
  ax["EXTENDED"]       = "Role::Unknown"
  ax["HEADER"]         = "Role::Unknown"
  ax["FOOTER"]         = "Role::Unknown"
  ax["PARAGRAPH"]      = "Role::Paragraph"
  ax["RULER"]          = "Role::Unknown"
  ax["APPLICATION"]    = "Role::Application"
  ax["AUTOCOMPLETE"]   = "Role::Unknown"
  ax["EDITBAR"]        = "Role::Unknown"
  ax["EMBEDDED"]       = "Role::Unknown"
  ax["ENTRY"]          = "Role::TextField"
  ax["CHART"]          = "Role::Unknown"
  ax["CAPTION"]        = "Role::Unknown"
  ax["DOCUMENT_FRAME"] = "Role::Unknown"
  ax["HEADING"]        = "Role::Heading"
  ax["PAGE"]           = "Role::Unknown"
  ax["SECTION"]        = "Role::Unknown"
  ax["REDUNDANT_OBJECT"] = "Role::Unknown"
  ax["FORM"]           = "Role::Unknown"
  ax["LINK"]           = "Role::Link"
  ax["INPUT_METHOD_WINDOW"] = "Role::Unknown"
  ax["TABLE_ROW"]      = "Role::Row"
  ax["TREE_ITEM"]      = "Role::TreeItem"
  ax["DOCUMENT_SPREADSHEET"] = "Role::Unknown"
  ax["DOCUMENT_PRESENTATION"] = "Role::Unknown"
  ax["DOCUMENT_TEXT"]  = "Role::Unknown"
  ax["DOCUMENT_WEB"]   = "Role::Unknown"
  ax["DOCUMENT_EMAIL"] = "Role::Unknown"
  ax["COMMENT"]        = "Role::Unknown"
  ax["LIST_BOX"]       = "Role::Unknown"
  ax["GROUPING"]       = "Role::Group"
  ax["IMAGE_MAP"]      = "Role::Unknown"
  ax["NOTIFICATION"]   = "Role::Alert"
  ax["INFO_BAR"]       = "Role::Unknown"
  ax["LEVEL_BAR"]      = "Role::Unknown"
  ax["TITLE_BAR"]      = "Role::Unknown"
  ax["BLOCK_QUOTE"]    = "Role::Unknown"
  ax["AUDIO"]          = "Role::Unknown"
  ax["VIDEO"]          = "Role::Unknown"
  ax["DEFINITION"]     = "Role::Unknown"
  ax["ARTICLE"]        = "Role::Unknown"
  ax["LANDMARK"]       = "Role::Unknown"
  ax["LOG"]            = "Role::Unknown"
  ax["MARQUEE"]        = "Role::Unknown"
  ax["MATH"]           = "Role::Unknown"
  ax["RATING"]         = "Role::Unknown"
  ax["TIMER"]          = "Role::Unknown"
  ax["STATIC"]         = "Role::StaticText"
  ax["MATH_FRACTION"]  = "Role::Unknown"
  ax["MATH_ROOT"]      = "Role::Unknown"
  ax["SUBSCRIPT"]      = "Role::Unknown"
  ax["SUPERSCRIPT"]    = "Role::Unknown"
  ax["DESCRIPTION_LIST"] = "Role::Unknown"
  ax["DESCRIPTION_TERM"] = "Role::Unknown"
  ax["DESCRIPTION_VALUE"] = "Role::Unknown"
  ax["FOOTNOTE"]       = "Role::Unknown"
  ax["CONTENT_DELETION"] = "Role::Unknown"
  ax["CONTENT_INSERTION"] = "Role::Unknown"
  ax["MARK"]           = "Role::Unknown"
  ax["SUGGESTION"]     = "Role::Unknown"
  ax["PUSH_BUTTON_MENU"] = "Role::Unknown"
  ax["LAST_DEFINED"]   = "Role::Unknown"
  ax["SWITCH"]         = "Role::Switch"
}
' "$HEADER"
