#!/usr/bin/env bash
# Generates src/platform/linux/atspi_roles.rs from res/atspi-constants.h.
#
# Usage:
#   ./res/generate_atspi_roles.sh          # prints to stdout (pipe to file)
#   ./res/generate_atspi_roles.sh > file   # redirect to file
#
# Source of truth: res/atspi-constants.h (copied from
#   https://gitlab.gnome.org/GNOME/at-spi2-core/-/raw/HEAD/atspi/atspi-constants.h)
#
# The AX role mapping is opinionated (AT-SPI2 → AX-prefixed names).
# The enum values are factual. Both are generated so CI can detect drift.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
HEADER="$SCRIPT_DIR/atspi-constants.h"

if [[ ! -f "$HEADER" ]]; then
  echo "ERROR: $HEADER not found" >&2
  exit 1
fi

awk '
BEGIN {
  in_enum = 0
  val = 0
  print "// Generated by res/generate_atspi_roles.sh from res/atspi-constants.h."
  print "// Source: https://gitlab.gnome.org/GNOME/at-spi2-core/-/raw/HEAD/atspi/atspi-constants.h"
  print "// To regenerate: bash res/generate_atspi_roles.sh > src/platform/linux/atspi_roles.rs"
  print ""
  print "#![expect(clippy::match_same_arms, reason = \"AT-SPI2 roles legitimately map to the same AX role\")]"
  print ""
  print "/// Map AT-SPI2 role values to AX-prefixed role strings."
  print "///"
  print "/// Generated from `res/atspi-constants.h`. See the generator for the AX mapping."
  print "#[must_use]"
  print "#[expect(clippy::too_many_lines, reason = \"generated match arm list\")]"
  print "#[rustfmt::skip]"
  print "pub fn atspi_role_to_role(role: u32) -> &'"'"'static str {"
  print "    match role {"
}

/typedef enum/ { in_enum = 1; next }
/^[[:space:]]*}/ && in_enum { in_enum = 0; next }

in_enum && /^[[:space:]]*ATSPI_ROLE_/ && !/=/ {
  gsub(/^[[:space:]]+/, "")
  gsub(/[[:space:]]+$/, "")
  gsub(/,$/, "")
  name = $1
  sub(/^ATSPI_ROLE_/, "", name)
  printf "        %d => \"%s\",\n", val, ax[name]
  val++
}

END {
  print "        _ => \"AXUnknown\","
  print "    }"
  print "}"
}

BEGIN {
  ax["INVALID"]        = "AXUnknown"
  ax["ACCELERATOR_LABEL"] = "AXUnknown"
  ax["ALERT"]          = "AXAlert"
  ax["ANIMATION"]      = "AXUnknown"
  ax["ARROW"]          = "AXUnknown"
  ax["CALENDAR"]       = "AXCalendar"
  ax["CANVAS"]         = "AXUnknown"
  ax["CHECK_BOX"]      = "AXCheckBox"
  ax["CHECK_MENU_ITEM"] = "AXMenuItemCheckBox"
  ax["COLOR_CHOOSER"]  = "AXColorChooser"
  ax["COLUMN_HEADER"]  = "AXColumnHeader"
  ax["COMBO_BOX"]      = "AXComboBox"
  ax["DATE_EDITOR"]    = "AXDatePicker"
  ax["DESKTOP_ICON"]   = "AXUnknown"
  ax["DESKTOP_FRAME"]  = "AXUnknown"
  ax["DIAL"]           = "AXUnknown"
  ax["DIALOG"]         = "AXDialog"
  ax["DIRECTORY_PANE"] = "AXUnknown"
  ax["DRAWING_AREA"]   = "AXUnknown"
  ax["FILE_CHOOSER"]   = "AXUnknown"
  ax["FILLER"]         = "AXUnknown"
  ax["FOCUS_TRAVERSABLE"] = "AXUnknown"
  ax["FONT_CHOOSER"]   = "AXUnknown"
  ax["FRAME"]          = "AXFrame"
  ax["GLASS_PANE"]     = "AXUnknown"
  ax["HTML_CONTAINER"] = "AXUnknown"
  ax["ICON"]           = "AXIcon"
  ax["IMAGE"]          = "AXImage"
  ax["INTERNAL_FRAME"] = "AXInternalFrame"
  ax["LABEL"]          = "AXLabel"
  ax["LAYERED_PANE"]   = "AXUnknown"
  ax["LIST"]           = "AXList"
  ax["LIST_ITEM"]      = "AXUnknown"
  ax["MENU"]           = "AXMenu"
  ax["MENU_BAR"]       = "AXMenuBar"
  ax["MENU_ITEM"]      = "AXMenuItem"
  ax["OPTION_PANE"]    = "AXUnknown"
  ax["PAGE_TAB"]       = "AXTab"
  ax["PAGE_TAB_LIST"]  = "AXTabGroup"
  ax["PANEL"]          = "AXGroup"
  ax["PASSWORD_TEXT"]  = "AXSecureTextField"
  ax["POPUP_MENU"]     = "AXMenu"
  ax["PROGRESS_BAR"]   = "AXProgressBar"
  ax["BUTTON"]         = "AXButton"
  ax["RADIO_BUTTON"]   = "AXRadioButton"
  ax["RADIO_MENU_ITEM"] = "AXMenuItemRadio"
  ax["ROOT_PANE"]      = "AXUnknown"
  ax["ROW_HEADER"]     = "AXRowHeader"
  ax["SCROLL_BAR"]     = "AXScrollBar"
  ax["SCROLL_PANE"]    = "AXUnknown"
  ax["SEPARATOR"]      = "AXSeparator"
  ax["SLIDER"]         = "AXSlider"
  ax["SPIN_BUTTON"]    = "AXIncrementor"
  ax["SPLIT_PANE"]     = "AXUnknown"
  ax["STATUS_BAR"]     = "AXStatusBar"
  ax["TABLE"]          = "AXTable"
  ax["TABLE_CELL"]     = "AXCell"
  ax["TABLE_COLUMN_HEADER"] = "AXColumnHeader"
  ax["TABLE_ROW_HEADER"] = "AXRowHeader"
  ax["TEAROFF_MENU_ITEM"] = "AXMenuItem"
  ax["TERMINAL"]       = "AXUnknown"
  ax["TEXT"]           = "AXTextArea"
  ax["TOGGLE_BUTTON"]  = "AXSwitch"
  ax["TOOL_BAR"]       = "AXToolBar"
  ax["TOOL_TIP"]       = "AXUserInterfaceTooltip"
  ax["TREE"]           = "AXOutline"
  ax["TREE_TABLE"]     = "AXUnknown"
  ax["UNKNOWN"]        = "AXUnknown"
  ax["VIEWPORT"]       = "AXUnknown"
  ax["WINDOW"]         = "AXWindow"
  ax["EXTENDED"]       = "AXUnknown"
  ax["HEADER"]         = "AXUnknown"
  ax["FOOTER"]         = "AXUnknown"
  ax["PARAGRAPH"]      = "AXParagraph"
  ax["RULER"]          = "AXUnknown"
  ax["APPLICATION"]    = "AXApplication"
  ax["AUTOCOMPLETE"]   = "AXUnknown"
  ax["EDITBAR"]        = "AXUnknown"
  ax["EMBEDDED"]       = "AXUnknown"
  ax["ENTRY"]          = "AXTextField"
  ax["CHART"]          = "AXUnknown"
  ax["CAPTION"]        = "AXUnknown"
  ax["DOCUMENT_FRAME"] = "AXUnknown"
  ax["HEADING"]        = "AXHeading"
  ax["PAGE"]           = "AXUnknown"
  ax["SECTION"]        = "AXUnknown"
  ax["REDUNDANT_OBJECT"] = "AXUnknown"
  ax["FORM"]           = "AXUnknown"
  ax["LINK"]           = "AXLink"
  ax["INPUT_METHOD_WINDOW"] = "AXUnknown"
  ax["TABLE_ROW"]      = "AXRow"
  ax["TREE_ITEM"]      = "AXTreeItem"
  ax["DOCUMENT_SPREADSHEET"] = "AXUnknown"
  ax["DOCUMENT_PRESENTATION"] = "AXUnknown"
  ax["DOCUMENT_TEXT"]  = "AXUnknown"
  ax["DOCUMENT_WEB"]   = "AXUnknown"
  ax["DOCUMENT_EMAIL"] = "AXUnknown"
  ax["COMMENT"]        = "AXUnknown"
  ax["LIST_BOX"]       = "AXUnknown"
  ax["GROUPING"]       = "AXGroup"
  ax["IMAGE_MAP"]      = "AXUnknown"
  ax["NOTIFICATION"]   = "AXAlert"
  ax["INFO_BAR"]       = "AXUnknown"
  ax["LEVEL_BAR"]      = "AXUnknown"
  ax["TITLE_BAR"]      = "AXUnknown"
  ax["BLOCK_QUOTE"]    = "AXUnknown"
  ax["AUDIO"]          = "AXUnknown"
  ax["VIDEO"]          = "AXUnknown"
  ax["DEFINITION"]     = "AXUnknown"
  ax["ARTICLE"]        = "AXUnknown"
  ax["LANDMARK"]       = "AXUnknown"
  ax["LOG"]            = "AXUnknown"
  ax["MARQUEE"]        = "AXUnknown"
  ax["MATH"]           = "AXUnknown"
  ax["RATING"]         = "AXUnknown"
  ax["TIMER"]          = "AXUnknown"
  ax["STATIC"]         = "AXStaticText"
  ax["MATH_FRACTION"]  = "AXUnknown"
  ax["MATH_ROOT"]      = "AXUnknown"
  ax["SUBSCRIPT"]      = "AXUnknown"
  ax["SUPERSCRIPT"]    = "AXUnknown"
  ax["DESCRIPTION_LIST"] = "AXUnknown"
  ax["DESCRIPTION_TERM"] = "AXUnknown"
  ax["DESCRIPTION_VALUE"] = "AXUnknown"
  ax["FOOTNOTE"]       = "AXUnknown"
  ax["CONTENT_DELETION"] = "AXUnknown"
  ax["CONTENT_INSERTION"] = "AXUnknown"
  ax["MARK"]           = "AXUnknown"
  ax["SUGGESTION"]     = "AXUnknown"
  ax["PUSH_BUTTON_MENU"] = "AXUnknown"
  ax["LAST_DEFINED"]   = "AXUnknown"
  ax["SWITCH"]         = "AXSwitch"
}
' "$HEADER"
