// Generated by res/generate_atspi_data.sh from res/atspi-constants.h.
// Source: https://gitlab.gnome.org/GNOME/at-spi2-core/-/raw/HEAD/atspi/atspi-constants.h
// To regenerate: bash res/generate_atspi_data.sh

//! AT-SPI2 `StateType` constants (values from `res/atspi-constants.h`).
//!
//! `org.a11y.atspi.Accessible.GetState` returns the `StateSet` as a 64-bit
//! bitmask across 32-bit words (word 0 = states 0-31, word 1 = 32-63);
//! these constants name the bit indices.

#![allow(dead_code)]
pub(crate) const STATE_INVALID: u32 = 0;
pub(crate) const STATE_ACTIVE: u32 = 1;
pub(crate) const STATE_ARMED: u32 = 2;
pub(crate) const STATE_BUSY: u32 = 3;
pub(crate) const STATE_CHECKED: u32 = 4;
pub(crate) const STATE_COLLAPSED: u32 = 5;
pub(crate) const STATE_DEFUNCT: u32 = 6;
pub(crate) const STATE_EDITABLE: u32 = 7;
pub(crate) const STATE_ENABLED: u32 = 8;
pub(crate) const STATE_EXPANDABLE: u32 = 9;
pub(crate) const STATE_EXPANDED: u32 = 10;
pub(crate) const STATE_FOCUSABLE: u32 = 11;
pub(crate) const STATE_FOCUSED: u32 = 12;
pub(crate) const STATE_HAS_TOOLTIP: u32 = 13;
pub(crate) const STATE_HORIZONTAL: u32 = 14;
pub(crate) const STATE_ICONIFIED: u32 = 15;
pub(crate) const STATE_MODAL: u32 = 16;
pub(crate) const STATE_MULTI_LINE: u32 = 17;
pub(crate) const STATE_MULTISELECTABLE: u32 = 18;
pub(crate) const STATE_OPAQUE: u32 = 19;
pub(crate) const STATE_PRESSED: u32 = 20;
pub(crate) const STATE_RESIZABLE: u32 = 21;
pub(crate) const STATE_SELECTABLE: u32 = 22;
pub(crate) const STATE_SELECTED: u32 = 23;
pub(crate) const STATE_SENSITIVE: u32 = 24;
pub(crate) const STATE_SHOWING: u32 = 25;
pub(crate) const STATE_SINGLE_LINE: u32 = 26;
pub(crate) const STATE_STALE: u32 = 27;
pub(crate) const STATE_TRANSIENT: u32 = 28;
pub(crate) const STATE_VERTICAL: u32 = 29;
pub(crate) const STATE_VISIBLE: u32 = 30;
pub(crate) const STATE_MANAGES_DESCENDANTS: u32 = 31;
pub(crate) const STATE_INDETERMINATE: u32 = 32;
pub(crate) const STATE_REQUIRED: u32 = 33;
pub(crate) const STATE_TRUNCATED: u32 = 34;
pub(crate) const STATE_ANIMATED: u32 = 35;
pub(crate) const STATE_INVALID_ENTRY: u32 = 36;
pub(crate) const STATE_SUPPORTS_AUTOCOMPLETION: u32 = 37;
pub(crate) const STATE_SELECTABLE_TEXT: u32 = 38;
pub(crate) const STATE_IS_DEFAULT: u32 = 39;
pub(crate) const STATE_VISITED: u32 = 40;
pub(crate) const STATE_CHECKABLE: u32 = 41;
pub(crate) const STATE_HAS_POPUP: u32 = 42;
pub(crate) const STATE_READ_ONLY: u32 = 43;
pub(crate) const STATE_LAST_DEFINED: u32 = 44;
